version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  commit:
    jobs:
      - build 
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only: 
                - master
